global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "go_account"
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["172.17.0.1:5000"] # Adjust the IP and port as necessary, 172.17.0.1 is commonly the host machine from within Docker

  - job_name: "go_inventory"
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["172.17.0.1:7000"]
